# Generated by Django 4.2.7 on 2023-12-03 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('idAlojamiento', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_publi', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disponibilidad', models.BooleanField(default=False)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nac', models.DateField()),
                ('foto', models.ImageField(upload_to='fotos')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idAReserva', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('idAlojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.alojamiento')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('fecha_publi', models.DateTimeField(auto_now_add=True)),
                ('idAlojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.alojamiento')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Arrendador',
            fields=[
                ('idArrendador', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nac', models.DateField()),
                ('dni', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.usuario'),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='idArrendador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquiler.arrendador'),
        ),
    ]
